version: '3.8'
services:
  directus:
    image: directus/directus:latest
    ports:
      - "8055:8055" # Directus admin panel
    environment:
      DATABASE_CLIENT: mongodb
      DATABASE_HOST: mongodb
      DATABASE_PORT: 27017
      DATABASE_NAME: blogdb
      ADMIN_EMAIL: admin@example.com
      ADMIN_PASSWORD: admin123
    depends_on:
      - mongodb
      - fastapi
    volumes:
      - ./directus-data:/data # Optional: Persist Directus data

  mongodb:
    image: bitnami/mongodb:latest
    ports:
      - "27017:27017" # MongoDB port
    environment:
      MONGODB_DATABASE: blogdb
      MONGODB_ROOT_USER: root
      MONGODB_ROOT_PASSWORD: rootpassword
    volumes:
      - ./mongo-data:/bitnami/mongodb # Optional: Persist MongoDB data

  fastapi:
    build: ./fastapi
    ports:
      - "8000:8000" # FastAPI port
    volumes:
      - ./fastapi:/app