version: '3.8'
services:
  directus:
    image: directus/directus:latest
    ports:
      - "8055:8055" # Directus admin panel
    environment:
      DATABASE_CLIENT: mongodb
      DATABASE_HOST: mongodb
      DATABASE_PORT: 27017
      DATABASE_NAME: blogdb
      ADMIN_EMAIL: admin@example.com
      ADMIN_PASSWORD: admin123
    depends_on:
      - mongodb
      - fastapi
    volumes:
      - ./directus-data:/data # Optional: Persist Directus data


  mongodb:
  image: mongo:4.4
  ports:
    - "27017:27017"
  environment:
    MONGO_INITDB_ROOT_USERNAME: root
    MONGO_INITDB_ROOT_PASSWORD: rootpassword
  volumes:
    - ./mongo-data:/data/db

  fastapi:
    build: ./fastapi
    ports:
      - "8000:8000" # FastAPI port
    volumes:
      - ./fastapi:/app